# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tdf_open <- function(path, db_path) {
    .Call('_opentims_tdf_open', PACKAGE = 'opentims', path, db_path)
}

tdf_open_dir <- function(path) {
    .Call('_opentims_tdf_open_dir', PACKAGE = 'opentims', path)
}

tdf_min_frame_id <- function(tdf) {
    .Call('_opentims_tdf_min_frame_id', PACKAGE = 'opentims', tdf)
}

tdf_max_frame_id <- function(tdf) {
    .Call('_opentims_tdf_max_frame_id', PACKAGE = 'opentims', tdf)
}

tdf_no_peaks_total <- function(tdf) {
    .Call('_opentims_tdf_no_peaks_total', PACKAGE = 'opentims', tdf)
}

tdf_get_range <- function(tdf, start, end, step = 1L) {
    .Call('_opentims_tdf_get_range', PACKAGE = 'opentims', tdf, start, end, step)
}

tdf_get_indexes <- function(tdf, indexes) {
    .Call('_opentims_tdf_get_indexes', PACKAGE = 'opentims', tdf, indexes)
}

tdf_get_range_noend <- function(tdf, start, step = 1L) {
    .Call('_opentims_tdf_get_range_noend', PACKAGE = 'opentims', tdf, start, step)
}

