# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.setup_bruker_so <- function(path) {
    invisible(.Call('_opentimsr_setup_bruker_so', PACKAGE = 'opentimsr', path))
}

tdf_open <- function(path_d) {
    .Call('_opentimsr_tdf_open', PACKAGE = 'opentimsr', path_d)
}

tdf_min_frame_id <- function(tdf) {
    .Call('_opentimsr_tdf_min_frame_id', PACKAGE = 'opentimsr', tdf)
}

tdf_max_frame_id <- function(tdf) {
    .Call('_opentimsr_tdf_max_frame_id', PACKAGE = 'opentimsr', tdf)
}

tdf_no_peaks_total <- function(tdf) {
    .Call('_opentimsr_tdf_no_peaks_total', PACKAGE = 'opentimsr', tdf)
}

tdf_get_msms_type <- function(tdf) {
    .Call('_opentimsr_tdf_get_msms_type', PACKAGE = 'opentimsr', tdf)
}

tdf_get_range <- function(tdf, start, end, step = 1L) {
    .Call('_opentimsr_tdf_get_range', PACKAGE = 'opentimsr', tdf, start, end, step)
}

tdf_get_indexes <- function(tdf, indexes) {
    .Call('_opentimsr_tdf_get_indexes', PACKAGE = 'opentimsr', tdf, indexes)
}

tdf_get_range_noend <- function(tdf, start, step = 1L) {
    .Call('_opentimsr_tdf_get_range_noend', PACKAGE = 'opentimsr', tdf, start, step)
}

tdf_extract_frames <- function(tdf, indexes, get_frames = TRUE, get_scans = TRUE, get_tofs = TRUE, get_intensities = TRUE, get_mzs = TRUE, get_dts = TRUE, get_rts = TRUE) {
    .Call('_opentimsr_tdf_extract_frames', PACKAGE = 'opentimsr', tdf, indexes, get_frames, get_scans, get_tofs, get_intensities, get_mzs, get_dts, get_rts)
}

tdf_extract_frames_slice <- function(tdf, start, end, step = 1L, get_frames = TRUE, get_scans = TRUE, get_tofs = TRUE, get_intensities = TRUE, get_mzs = TRUE, get_dts = TRUE, get_rts = TRUE) {
    .Call('_opentimsr_tdf_extract_frames_slice', PACKAGE = 'opentimsr', tdf, start, end, step, get_frames, get_scans, get_tofs, get_intensities, get_mzs, get_dts, get_rts)
}

