name: Build

on:
  push:
    branches:
      - ci-test
    tags:
      - v*
  workflow_call:

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-15-intel, macos-latest]

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5

      - name: Check version
        run: python .github/scripts/check_version.py

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          GITHUB_BUILDING_WHEELS: 1
          VERBOSE: 1
          MACOSX_DEPLOYMENT_TARGET: "10.13"
          CIBW_ENABLE: "pypy"
          CIBW_BUILD: "cp* pp*"
          CIBW_SKIP: "cp39-win_arm64 cp310-win_arm64"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Check version
        run: python .github/scripts/check_version.py

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz
